/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-01-20 07:09:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/base.css\" type=\"text/css\"></link>\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/member/signup.css\" type=\"text/css\"></link>\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/agreement-middle.css\" type=\"text/css\"></link>\n");
      out.write("<script src=\"/js/ajax/ajaxID.js\" type=\"text/javascript\" defer></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"\n");
      out.write("\tintegrity=\"sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=\"\n");
      out.write("\tcrossorigin=\"anonymous\" defer></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<header>\n");
      out.write("\t\t<a href=\"/\"> <img src=\"/css/picture/owlsLogo.png\" alt=\"로고사진\">\n");
      out.write("\t\t</a>\n");
      out.write("\t</header>\n");
      out.write("\t<section>\n");
      out.write("\t\t<div class=\"signup__form\">\n");
      out.write("\t\t\t<form action=\"/member/signupProc\" method=\"post\" id=\"ckpoint\">\n");
      out.write("\t\t\t\t<div class=\"signup__id\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"아이디\" name=\"id\" id=\"id\" oninput=\"checkId()\" maxlength=\"10\">\n");
      out.write("\t\t\t\t\t<p class=\"id__text\"></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"signup__pwd\">\n");
      out.write("\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호\" name=\"pw\" id=\"pw\"\n");
      out.write("\t\t\t\t\t\tmaxlength=\"10\">\n");
      out.write("\t\t\t\t\t<p class=\"pw__text\"></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"signup__pwd_check\">\n");
      out.write("\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호 재확인\" name=\"cpw\" id=\"cpw\"\n");
      out.write("\t\t\t\t\t\tmaxlength=\"10\">\n");
      out.write("\t\t\t\t\t<p class=\"cpw__text\"></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"signup__name\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"이름\" name=\"name\" id=\"name\"\n");
      out.write("\t\t\t\t\t\tmaxlength=\"6\">\n");
      out.write("\t\t\t\t\t<p class=\"name__text\"></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"signup__phone\">\n");
      out.write("\t\t\t\t\t<input type=\"tel\" placeholder=\"전화번호\" name=\"tel\" id=\"tel\"\n");
      out.write("\t\t\t\t\t\tmaxlength=\"11\">\n");
      out.write("\t\t\t\t\t<p class=\"tel__text\"></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"signup__gender\">\n");
      out.write("\t\t\t\t\t<select name=\"gender\" id=\"gender\">\n");
      out.write("\t\t\t\t\t\t<option value=\"남\">남성</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"여\">여성</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"signup__agree\">\n");
      out.write("\t\t\t\t\t<div class=\"agree__container\">\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"agree__text\">개인정보동의(필수)</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"info_fl\" id=\"info_fl\" value=\"true\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"agree__container\">\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"agree__text\">광고수신동의(선택)</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"sms_fl\" id=\"sms_fl\" value=\"true\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<div class=\"btn-container\">\n");
      out.write("\t\t\t\t<button id=\"signup__button\" onclick=\"join()\">가입하기</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"signup__line\">또는 다른 것이 필요하신가요?</div>\n");
      out.write("\t\t\t<div class=\"sign__up__kakao\">\n");
      out.write("\t\t\t\t<a id=\"kakao-text\" href=\"#\">카카오톡으로 회원가입</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"sign__up__naver\">\n");
      out.write("\t\t\t\t<a id=\"naver-text\" href=\"#\">네이버로 회원가입</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<footer>\n");
      out.write("\t\t<span class=\"signup__form\">\n");
      out.write("\t\t\t로그인하거나 회원으로 가입하시면 당사\n");
      out.write("\t\t\t<a href=\"#\" class=\"agreement\"onclick=\"createFeed()\">이용약관</a>\n");
      out.write("\t\t\t 및\n");
      out.write("\t\t\t<a href=\"#\" onclick=\"createFeed()\"class=\"agreement\">개인정보 보호정책</a>\n");
      out.write("\t\t\t <p>에 동의하시는 것으로 간주됩니다.</p>\n");
      out.write("\t\t</span>\n");
      out.write("\t</footer>\n");
      out.write("\t<script src=\"/js/agreement/agree.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"/js/member/signup.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"/js/member/ajax.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
