/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-01-20 05:13:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import shop.steamowls.steam.booking.vo.BookingVo;
import shop.steamowls.common.LoginManager;
import java.util.ArrayList;

public final class Bhistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("shop.steamowls.steam.booking.vo.BookingVo");
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	ArrayList<BookingVo> list = (ArrayList<BookingVo>) request.getAttribute("list");
	BookingVo bookingVo = (BookingVo) request.getAttribute("bookingVo");
	BookingVo productInfoVo = (BookingVo) request.getAttribute("productInfoVo");
	LoginManager lm = LoginManager.getInstance();
	String sq = lm.getMemberSq(session);
	DecimalFormat won = new DecimalFormat("###,###");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t<title>예약내역</title>\n");
      out.write("\t<link href=\"/css/picture/icons8_owl.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/mypage/Bhistory.css\">\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"tt\">\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header-logout.jsp", out, false);
      out.write("\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<section>\n");
      out.write("\t\t\t");

				for (int i = 0; i < list.size(); i++) {
			
      out.write("\n");
      out.write("\t\t\t<article>\n");
      out.write("\t\t\t\t<div class=\"booking__container\">\n");
      out.write("\t\t\t\t\t<div class=\"booking__img\">\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.get(i).getProduct_imagePath());
      out.write("\n");
      out.write("\t\t\t\t\t\t<img alt=\"\" src=\"/css/picture/Spa.png\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"booking__top\">\n");
      out.write("\t\t\t\t\t\t<div class=\"booking__title\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"booking__title\">예약상품</h3>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"booking__text\">\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(list.get(i).getProduct_name());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"booking__intro\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"booking__title\">예약일자</h3>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"booking__text\">\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(list.get(i).getBooking_date());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(list.get(i).getBooking_start());
      out.write("시\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"booking__bottom\">\n");
      out.write("\t\t\t\t\t\t<div class=\"booking__people\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"booking__title\">예약인원</h3>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"booking__text\">\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(list.get(i).getBooking_people());
      out.write("명\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"booking__price\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"booking__title\">결제금액</h3>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"booking__text\">\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(won.format(list.get(i).getProduct_price() * list.get(i).getBooking_people()));
      out.write("원</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"btn__container\">\n");
      out.write("\t\t\t\t\t\t<a id=\"ckpoint\" href=\"/mypage/BCancel?booking_sq=");
      out.print(list.get(i).getBooking_sq());
      out.write("\">예약취소</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</article>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\t</div>\n");
      out.write("\t<footer>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
