/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-01-21 05:34:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.steamowls.common.LoginManager;
import shop.steamowls.steam.mypage.vo.MypageVo;

public final class RmyReviewModify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
    _jspx_imports_classes.add("shop.steamowls.steam.mypage.vo.MypageVo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	MypageVo mypageVo = (MypageVo) request.getAttribute("vo");
LoginManager lm = LoginManager.getInstance();
String sq = lm.getMemberSq(session);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>리뷰수정</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/mypage/Rmodify.css\">\n");
      out.write("\t<script  src=\"/js/mypage/Rmodify.js\" defer></script>\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<section>\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header-logout.jsp", out, false);
      out.write("\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<section>\n");
      out.write("\t\t\t<form action=\"/mypage/RmyReviewModifyProc?review_sq=");
      out.print(mypageVo.getReview_sq() );
      out.write("\" method=\"post\" id=\"editorForm\">\n");
      out.write("\t\t\t\t<div class=\"review__container\">\n");
      out.write("\t\t\t\t<div class=\"review__title\">\n");
      out.write("\t\t\t\t\t<h3>제목</h3>\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"review__text\" name=\"review_subject\"\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(mypageVo.getReview_subject());
      out.write("\" />\n");
      out.write("\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"review__content\">\n");
      out.write("\t\t\t\t\t<h3>이용후기</h3>\n");
      out.write("\t\t\t\t\t<textarea rows=\"10\" cols=\"30\" class=\"review_content\"\n");
      out.write("\t\t\t\t\t\tname=\"review_content\">");
      out.print(mypageVo.getReview_content());
      out.write("</textarea>\n");
      out.write("\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"review__star\">\n");
      out.write("\t\t\t\t\t<h3>평점</h3>\n");
      out.write("\t\t\t\t\t<div class=\"review__star\">\n");
      out.write("\t\t\t\t\t\t<div class=\"startRadio\">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"0.5\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 1개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"1.0\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 1.5개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"1.5\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 2개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"2.0\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 2.5개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"2.5\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 3개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"3.0\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 3.5개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"3.5\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 4개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"4.0\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 4.5개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"4.5\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 5개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"startRadio__box\"> <input type=\"radio\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"review_star\" id=\"\" value=\"5.0\"> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"startRadio__img\"><span class=\"blind\">별 5.5개</span></span>\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"btn__container\">\n");
      out.write("\t\t\t\t\t");

						if (Integer.parseInt(sq) == mypageVo.getSq()) {
					
      out.write("\n");
      out.write("\t\t\t\t\t<button id=\"modifyBtn\">수정</button>\n");
      out.write("\t\t\t\t\t<a href=\"/mypage/RmyReviewDetail?review_sq=");
      out.print(mypageVo.getReview_sq());
      out.write("\">취소</a>\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</section>\t\n");
      out.write("\t\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
