/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-01-22 05:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.steamowls.steam.mypage.vo.BoardVo;
import shop.steamowls.steam.admin.review.vo.ReviewVo;
import java.util.ArrayList;
import shop.steamowls.steam.mypage.vo.MypageVo;
import shop.steamowls.common.LoginManager;
import shop.steamowls.common.LoginManager;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
    _jspx_imports_classes.add("shop.steamowls.steam.mypage.vo.BoardVo");
    _jspx_imports_classes.add("shop.steamowls.steam.admin.review.vo.ReviewVo");
    _jspx_imports_classes.add("shop.steamowls.steam.mypage.vo.MypageVo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	LoginManager lm = LoginManager.getInstance();
String sq = lm.getMemberSq(session);
MypageVo mypageVo = (MypageVo) request.getAttribute("vo");
ArrayList<MypageVo> list = (ArrayList<MypageVo>) request.getAttribute("list");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("<title>Owls</title>\n");
      out.write("<link href=\"/css/picture/icons8_owl.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://npmcdn.com/flatpickr/dist/themes/airbnb.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/home/index.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/agreement.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/mypage/Rwriting.css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.js\" defer></script>\n");
      out.write("<script src=\"/js/common/calendar.js\" defer></script>\n");
      out.write("<script src=\"/js/agreement/agree.js\" defer></script>\n");
      out.write("<script src=\"/js/home/index.js\" defer></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		if (sq == null) {
	
      out.write("\n");
      out.write("\t<header>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\t</header>\n");
      out.write("\t<section>\n");
      out.write("\t\t<form action=\"/booking/Blist\" id=\"ckpoint\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" class=\"form_input\" id=\"basicDate\"\n");
      out.write("\t\t\t\tplaceholder=\"언제가 편하신가요?\" name=\"booking_date\" data-input> <input\n");
      out.write("\t\t\t\ttype=\"text\" class=\"form_input\" id=\"basicTime\" placeholder=\"예약시간\"\n");
      out.write("\t\t\t\tname=\"booking_start\" data-input> <select\n");
      out.write("\t\t\t\tclass=\"form_input input__btn\" name=\"booking_people\">\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"1\">1명</option>\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"2\">2명</option>\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"3\">3명</option>\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"4\">4명</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<button type=\"submit\" class=\"form_input form_submit\">\n");
      out.write("\t\t\t\t<i class=\"fas fa-search\"></i>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div class=\"main__intro\"></div>\n");
      out.write("\t\t<div class=\"img__container\">\n");
      out.write("\t\t\t<img src=\"/css/picture/Spa.png\" alt=\"main\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<header>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header-logout.jsp", out, false);
      out.write("\n");
      out.write("\t</header>\n");
      out.write("\t`\n");
      out.write("\t<section>\n");
      out.write("\t\t<form action=\"/booking/Blist\" id=\"ckpoint\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" class=\"form_input\" id=\"basicDate\"\n");
      out.write("\t\t\t\tplaceholder=\"언제가 편하신가요?\" name=\"booking_date\" data-input> <input\n");
      out.write("\t\t\t\ttype=\"text\" class=\"form_input\" id=\"basicTime\" placeholder=\"예약시간\"\n");
      out.write("\t\t\t\tname=\"booking_start\" data-input> <select\n");
      out.write("\t\t\t\tclass=\"form_input input__btn\" name=\"booking_people\">\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"1\">1명</option>\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"2\">2명</option>\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"3\">3명</option>\n");
      out.write("\t\t\t\t<option class=\"form_input\" value=\"4\">4명</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<button type=\"submit\" class=\"form_input form_submit\">\n");
      out.write("\t\t\t\t<i class=\"fas fa-search\"></i>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div class=\"img__container\">\n");
      out.write("\t\t\t<img src=\"/css/picture/Spa.png\" alt=\"main\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("\t<section>\n");
      out.write("\t\t<div class=\"intro__container\">\n");
      out.write("\t\t\t\t<h1>수백만 명에 이르는 아울스 커뮤니티의 일원이 되어보세요.</h1>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"slider\">\n");
      out.write("\n");
      out.write("\t\t\t");

				for (int i = 1; i < list.size(); i++) {
			
      out.write("\n");
      out.write("\t\t\t<div class=\"slider__item\">\n");
      out.write("\t\t\t\t<!-- 박스 1 -->\n");
      out.write("\t\t\t\t<div class=\"review__box\">\n");
      out.write("\t\t\t\t\t<div class=\"review__top\">\n");
      out.write("\t\t\t\t\t\t<div class=\"review__title\">\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(list.get(i).getReview_subject());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"review__name\">\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(list.get(i).getId());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"review__star\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"star\"> <i class=\"fas fa-star\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(list.get(i).getReview_star());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"review__bottom\">\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.get(i).getReview_content());
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- 박스 1 -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- 박스2 -->\n");
      out.write("\t\t\t\t<div class=\"review__box\">\n");
      out.write("\t\t\t\t\t<div class=\"review__top\">\n");
      out.write("\t\t\t\t\t\t<div class=\"review__title\">\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(list.get(i-1).getReview_subject());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"review__name\">\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(list.get(i-1).getId());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"review__star\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"star\"> <i class=\"fas fa-star\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(list.get(i-1).getReview_star());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"review__bottom\">\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.get(i-1).getReview_content());
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- 박스2-->\n");
      out.write("\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"btn__container\">\n");
      out.write("\t\t\t<button class=\"btn prev\"><</button>\n");
      out.write("\t\t\t<button class=\"btn next\">></button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<section>\n");
      out.write("\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t<div class=\"intro__container\">\n");
      out.write("\t\t\t\t<h1>이제, 스파는</h1>\n");
      out.write("\t\t\t\t<h1>더 특별해진 아울스에서</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"info__container\">\n");
      out.write("\t\t\t\t<div class=\"info__box\">\n");
      out.write("\t\t\t\t\t<img src=\"/css/picture/picForSlide/massage-835468_1280.jpg\">\n");
      out.write("\t\t\t\t\t<div class=\"info__text\">헤드 마사지</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"info__box\">\n");
      out.write("\t\t\t\t\t<img src=\"/css/picture/picForSlide/treatment-1327811_1280.jpg\">\n");
      out.write("\t\t\t\t\t<div class=\"info__text\">지압</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"info__box\">\n");
      out.write("\t\t\t\t\t<img src=\"/css/picture/picForSlide/spa-3184610_1280.jpg\">\n");
      out.write("\t\t\t\t\t<div class=\"info__text\">핫스톤 마사지</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"info__box\">\n");
      out.write("\t\t\t\t\t<img src=\"/css/picture/picForSlide/massage-1929064_1280.jpg\">\n");
      out.write("\t\t\t\t\t<div class=\"info__text\">24시간 풀케어</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<footer>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
