/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-01-18 05:31:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.steamowls.common.LoginManager;
import shop.steamowls.steam.mypage.vo.BoardVo;
import shop.steamowls.common.Pagenation;
import java.util.ArrayList;

public final class Qmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
    _jspx_imports_classes.add("shop.steamowls.steam.mypage.vo.BoardVo");
    _jspx_imports_classes.add("shop.steamowls.common.Pagenation");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

ArrayList<BoardVo> list = (ArrayList<BoardVo>) request.getAttribute("list");
BoardVo boardVo = (BoardVo) request.getAttribute("boardVo");
LoginManager lm = LoginManager.getInstance();
String sq = lm.getMemberSq(session);
Pagenation pagenation = (Pagenation) request.getAttribute("pagenation");
String pn = request.getParameter("pn");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t<title>문의게시판</title>\n");
      out.write("\t<link href=\"/css/picture/icons8_owl.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<header>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header-logout.jsp", out, false);
      out.write("\n");
      out.write("\t</header>\n");
      out.write("\t<nav role=\"navigation\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/admin-nav.jsp", out, false);
      out.write("\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<h1>문의 관리</h1>\n");
      out.write("\t<br>\n");
      out.write("\t<div>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>문의번호</th>\n");
      out.write("\t\t\t<th>문의제목</th>\n");
      out.write("\t\t\t<th>문의자</th>\n");
      out.write("\t\t\t<th>문의날짜</th>\n");
      out.write("\t\t\t<th>문의답변여부</th>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");

	for (int i = 0; i < list.size(); i++) {
	
      out.write("\n");
      out.write("\t<div>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).getBoard_sq());
      out.write("</td>\n");
      out.write("\t\t\t<td><a\n");
      out.write("\t\t\t\t\thref=\"/admin/Qdetail?board_sq=");
      out.print(list.get(i).getBoard_sq());
      out.write('"');
      out.write('>');
      out.print(list.get(i).getBoard_subject());
      out.write("</a>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).getMember_id());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).getBoard_dttm());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).isAnswer_fl());
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<a href=\"/admin/Qanswer\">관리자 답변작성</a>\n");
      out.write("\t</div>\n");
      out.write("\t");

	}
	
      out.write("\n");
      out.write("\n");
      out.write("\t<div>\n");
      out.write("\t\t");

		if (pagenation.getStartPageNumber() != 1) {
		
      out.write("\n");
      out.write("\t\t<a href=\"/admin/Qmanage?pn=");
      out.print(pagenation.getStartPageNumber() - 1);
      out.write("\">prev</a>\n");
      out.write("\t\t");

		}
		
      out.write('\n');
      out.write('	');
      out.write('	');

		for (int i = pagenation.getStartPageNumber(); i <= pagenation.getEndPageNumber(); i++) {
			if (i != Integer.parseInt(pn)) {
		
      out.write("\n");
      out.write("\t\t<a href=\"/admin/Qmanage?pn=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\n");
      out.write("\t\t");

		} else {
		
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(i);
      out.write('\n');
      out.write('	');
      out.write('	');

		}
		}
		
      out.write('\n');
      out.write('	');
      out.write('	');

		if (pagenation.getEndPageNumber() != pagenation.getTotalPageCount()) {
		
      out.write("\n");
      out.write("\t\t<a href=\"/admin/Qmanage?pn=");
      out.print(pagenation.getStartPageNumber() + 1);
      out.write("\">next</a>\n");
      out.write("\t\t");

		}
		
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
