/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-29 03:07:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.steamowls.steam.admin.product.vo.ProductVo;
import java.util.ArrayList;
import shop.steamowls.steam.member.vo.MemberVo;
import shop.steamowls.common.LoginManager;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
    _jspx_imports_classes.add("shop.steamowls.steam.admin.product.vo.ProductVo");
    _jspx_imports_classes.add("shop.steamowls.steam.member.vo.MemberVo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	ArrayList<ProductVo> list = (ArrayList<ProductVo>) request.getAttribute("list");
MemberVo vo = (MemberVo) request.getAttribute("vo");
LoginManager lm = LoginManager.getInstance();
String sq = lm.getMemberSq(session);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>예약</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/booking/booking.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/c_header.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.1/css/all.css\"\n");
      out.write("\t\tintegrity=\"sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp\" crossorigin=\"anonymous\">\n");
      out.write("\t<script src=\"/js/booking/booking.js\" defer></script>\n");
      out.write("\t<script src=\"/js/common/c_header.js\" defer></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		if (sq == null) {
	
      out.write("\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\t<a href=\"/\">\n");
      out.write("\t\t\t\t\t<img src=\"/css/picture/owls.PNG\" alt=\"로고사진\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<ul class=\"signForm\">\n");
      out.write("\t\t\t\t\t<li class=\"toggle_btn\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-bars\"></i>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<ul class=\"toggle_bar\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/member/login\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/member/signup\">회원가입</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<header>\n");
      out.write("\t\t<a href=\"/\">\n");
      out.write("\t\t\t<img src=\"/css/picture/owls.PNG\" alt=\"로고사진\">\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<ul class=\"signForm\">\n");
      out.write("\t\t\t<li class=\"toggle_btn\">\n");
      out.write("\t\t\t\t<i class=\"fas fa-bars\"></i>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<ul class=\"toggle_bar\">\n");
      out.write("\t\t\t\t<li><a href=\"/mypage/gotoMypage\">마이페이지</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/member/logout\">로그아웃</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</header>\n");
      out.write("\t");

	}
	
      out.write('\n');
      out.write('	');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\t<section>\n");
      out.write("\t\t<div class=\"booking_container\">\n");
      out.write("\t\t\t<div class=\"form_img\">\n");
      out.write("\t\t\t\t<img src=\"/css/picture/massage-1017255_640.png\" alt=\"A코스\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form_top\">\n");
      out.write("\t\t\t\t<h3>A- 최상급 코스</h3>\n");
      out.write("\t\t\t\t<p class=\"form_intro\">이 코스는 인도에서 부터 유래되어 아주 영국으로 저기로 아무튼 프리미엄 입니다. </p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form_bottom\">\n");
      out.write("\t\t\t\t<div class=\"bottom_text\">\n");
      out.write("\t\t\t\t\t<span class=\"form_intro\">1인,</span>\n");
      out.write("\t\t\t\t\t<span class=\"form_intro\">성인 기준</span>\n");
      out.write("\t\t\t\t\t<span class=\"form_price\">$90,000</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<button class=\"booking_btn\" onclick=\"book()\">예약</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
