/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-29 03:07:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.steamowls.common.LoginManager;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

LoginManager lm = LoginManager.getInstance();
String sq = lm.getMemberSq(session);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>결제완료</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/booking/payment.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/c_header.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.15.1/css/all.css\"\n");
      out.write("\tintegrity=\"sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<script src=\"/js/common/c_header.js\" defer></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");

	 if (sq == null) {
	
      out.write("\n");
      out.write("\t<header>\n");
      out.write("\t\t<a href=\"/\"> <img src=\"/css/picture/owls.PNG\" alt=\"로고사진\">\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<ul class=\"signForm\">\n");
      out.write("\t\t\t<li class=\"toggle_btn\"><i class=\"fas fa-bars\"></i></li>\n");
      out.write("\t\t\t<ul class=\"toggle_bar\">\n");
      out.write("\t\t\t\t<li><a href=\"/member/login\">로그인</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/member/signup\">회원가입</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</header>\n");
      out.write("\t\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<header>\n");
      out.write("\t\t<a href=\"/\"> <img src=\"/css/picture/owls.PNG\" alt=\"로고사진\">\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<ul class=\"signForm\">\n");
      out.write("\t\t\t<li class=\"toggle_btn\"><i class=\"fas fa-bars\"></i></li>\n");
      out.write("\t\t\t<ul class=\"toggle_bar\">\n");
      out.write("\t\t\t\t<li><a href=\"/mypage/gotoMypage\">마이페이지</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/member/logout\">로그아웃</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</header>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\t<section>\n");
      out.write("\t\t<div class=\"pay_form\">\n");
      out.write("\t\t\t<div class=\"pay_info_container\">\n");
      out.write("\t\t\t\t<div class=\"pay_info\">\n");
      out.write("\t\t\t\t\t<h1 class=\"info_title cut_line\">예약 정보</h1>\n");
      out.write("\t\t\t\t\t<div class=\"info_date\">\n");
      out.write("\t\t\t\t\t\t<h3>날짜</h3>\n");
      out.write("\t\t\t\t\t\t<p class=\"intro_sub\">2020-12-25</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"info_people\">\n");
      out.write("\t\t\t\t\t\t<h3>인원</h3>\n");
      out.write("\t\t\t\t\t\t<p class=\"intro_sub cut_line\">인원 2명</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"pay_way cut_line\">\n");
      out.write("\t\t\t\t\t<h2>결제 수단</h2>\n");
      out.write("\t\t\t\t\t<select value=\"way\">\n");
      out.write("\t\t\t\t\t\t<option name=\"네이버페이\" id=\"\">네이버페이</option>\n");
      out.write("\t\t\t\t\t\t<option name=\"카카오페이\" id=\"\">카카오페이</option>\n");
      out.write("\t\t\t\t\t\t<option name=\"신용 카드\" id=\"\">신용 카드</option>\n");
      out.write("\t\t\t\t\t\t<option name=\"계좌이체\" id=\"\">계좌이체</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"pay_agree\">\n");
      out.write("\t\t\t\t\t<label for=\"agreement\">결제약관에 동의하신다면 확인해주세요.</label>\n");
      out.write("\t\t\t\t\t <input type=\"checkbox\" name=\"agreement\" id=\"agreement\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- <a href=\"/views/booking/bookingSuccess.jsp\">결제완료</a> -->\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"ckpoint\">\n");
      out.write("\t\t\t\t\t결제하기\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"pay_detail_container\">\n");
      out.write("\t\t\t\t<div class=\"detail_img_container\">\n");
      out.write("\t\t\t\t\t<div class=\"detail_img\">\n");
      out.write("\t\t\t\t\t\t<img src=\"/css/picture/massage-1017255_640.png\" alt=\"상품사진\">\n");
      out.write("\t\t\t\t\t\t<div class=\"intro_sub cut_line\">우리의 떙떙쓰 파리투나잇 와우 언빌리버블\n");
      out.write("\t\t\t\t\t\t\t마사즤입니다.</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"detail_info_container\">\n");
      out.write("\t\t\t\t\t<h1>요금 세부정보</h1>\n");
      out.write("\t\t\t\t\t<p class=\"intro_sub\">가격 16,000</p>\n");
      out.write("\t\t\t\t\t<p class=\"intro_sub\">인원 2명</p>\n");
      out.write("\t\t\t\t\t<p>총 합계 (KRW) 32,000</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<footer>\n");
      out.write("\t\t<!-- 추후에 작성해야함. -->\n");
      out.write("\t</footer>\n");
      out.write("\t<script src=\"/js/booking/payment.js\" defer></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
