/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-01-20 05:13:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.steamowls.steam.admin.member.vo.MemberVo;
import shop.steamowls.steam.booking.vo.BookingVo;
import shop.steamowls.common.LoginManager;

public final class Pinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("shop.steamowls.steam.admin.member.vo.MemberVo");
    _jspx_imports_classes.add("shop.steamowls.steam.booking.vo.BookingVo");
    _jspx_imports_classes.add("shop.steamowls.common.LoginManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

BookingVo bookingVo = (BookingVo) request.getAttribute("bookingVo");
MemberVo vo = (MemberVo) request.getAttribute("vo");
LoginManager lm = LoginManager.getInstance();
String sq = lm.getMemberSq(session);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>결제화면</title>\n");
      out.write("<link href=\"/css/picture/icons8_owl.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.1/css/all.css\" integrity=\"sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/agreement.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/booking/payment.css\">\n");
      out.write("<script src=\"/js/booking/payment.js\" defer></script>\n");
      out.write("<script src=\"/js/agreement/agree.js\" defer></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<header>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header-logout.jsp", out, false);
      out.write("\n");
      out.write("\t</header>\n");
      out.write("\t<section>\n");
      out.write("\t\t<form method=\"post\"\n");
      out.write("\t\t\taction=\"/booking/BpayResult?booking_date=");
      out.print(bookingVo.getBooking_date());
      out.write("\n");
      out.write("\t\t\t\t&booking_start=");
      out.print(bookingVo.getBooking_start());
      out.write("\n");
      out.write("\t\t\t\t&booking_people=");
      out.print(bookingVo.getBooking_people());
      out.write("\n");
      out.write("\t\t\t\t&product_price=");
      out.print(bookingVo.getProduct_price());
      out.write("\n");
      out.write("\t\t\t\t&product_name=");
      out.print(bookingVo.getProduct_name());
      out.write("\"\n");
      out.write("\t\t\t id=\"ckpoint\">\n");
      out.write("\t\t\t<div class=\"pay_way\">\n");
      out.write("\t\t\t\t<h2 class=\"pay_form\">결제 수단</h2>\n");
      out.write("\t\t\t\t<select value=\"way\" class=\"pay_form\">\n");
      out.write("\t\t\t\t\t<option name=\"네이버페이\" id=\"\">네이버페이</option>\n");
      out.write("\t\t\t\t\t<option name=\"카카오페이\" id=\"\">카카오페이</option>\n");
      out.write("\t\t\t\t\t<option name=\"신용 카드\" id=\"\">신용 카드</option>\n");
      out.write("\t\t\t\t\t<option name=\"계좌이체\" id=\"\">계좌이체</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"pay_agree\">\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"agreement\" id=\"agreement\"\n");
      out.write("\t\t\t\t\tclass=\"pay_form\"> <label for=\"agreement\" class=\"pay_form\">결제약관에\n");
      out.write("\t\t\t\t\t동의해주세요.</label>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"Pinfo_submit\">결제하기</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</section>\n");
      out.write("\t<footer>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
